"""Bundled English stopword list for n-gram summary construction.

We bundle the list rather than depending on an NLP toolkit because:

- ``kaos-nlp-core``'s ``Tokenizer`` already accepts a ``stopwords``
  list — but ships no canonical default for English. We need one.
- Adding NLTK / spaCy as a dependency for one constant value would
  be ridiculous.
- This list is small, stable, and the standard "Snowball / NLTK
  basic English" set used across the IR / NLP toolchain. Any model
  trained on web text knows these words don't carry topical signal.

Keep this list **conservative** — only words that are obviously
non-topical. Domain-specific stopwords (e.g. "party", "agreement"
in legal contracts, "company" in 10-Ks) should NOT live here:
those words are *exactly* what the top-n-gram pass is meant to
surface as the document's theme. Trimming them here would silently
remove signal.

The set is frozenset-typed for O(1) membership tests and to signal
intent (do not mutate).
"""

from __future__ import annotations

# Canonical English stopwords. Hand-curated from the Snowball / NLTK
# baseline lists with a few small additions for contractions.
ENGLISH_STOPWORDS: frozenset[str] = frozenset(
    {
        "a",
        "about",
        "above",
        "after",
        "again",
        "against",
        "all",
        "am",
        "an",
        "and",
        "any",
        "are",
        "aren",
        "aren't",
        "as",
        "at",
        "be",
        "because",
        "been",
        "before",
        "being",
        "below",
        "between",
        "both",
        "but",
        "by",
        "can",
        "couldn",
        "couldn't",
        "did",
        "didn",
        "didn't",
        "do",
        "does",
        "doesn",
        "doesn't",
        "doing",
        "don",
        "don't",
        "down",
        "during",
        "each",
        "few",
        "for",
        "from",
        "further",
        "had",
        "hadn",
        "hadn't",
        "has",
        "hasn",
        "hasn't",
        "have",
        "haven",
        "haven't",
        "having",
        "he",
        "her",
        "here",
        "hers",
        "herself",
        "him",
        "himself",
        "his",
        "how",
        "i",
        "if",
        "in",
        "into",
        "is",
        "isn",
        "isn't",
        "it",
        "it's",
        "its",
        "itself",
        "just",
        "ll",
        "m",
        "ma",
        "me",
        "mightn",
        "mightn't",
        "more",
        "most",
        "mustn",
        "mustn't",
        "my",
        "myself",
        "needn",
        "needn't",
        "no",
        "nor",
        "not",
        "now",
        "o",
        "of",
        "off",
        "on",
        "once",
        "only",
        "or",
        "other",
        "our",
        "ours",
        "ourselves",
        "out",
        "over",
        "own",
        "re",
        "s",
        "same",
        "shan",
        "shan't",
        "she",
        "she's",
        "should",
        "should've",
        "shouldn",
        "shouldn't",
        "so",
        "some",
        "such",
        "t",
        "than",
        "that",
        "that'll",
        "the",
        "their",
        "theirs",
        "them",
        "themselves",
        "then",
        "there",
        "these",
        "they",
        "this",
        "those",
        "through",
        "to",
        "too",
        "under",
        "until",
        "up",
        "ve",
        "very",
        "was",
        "wasn",
        "wasn't",
        "we",
        "were",
        "weren",
        "weren't",
        "what",
        "when",
        "where",
        "which",
        "while",
        "who",
        "whom",
        "why",
        "will",
        "with",
        "won",
        "won't",
        "wouldn",
        "wouldn't",
        "y",
        "you",
        "you'd",
        "you'll",
        "you're",
        "you've",
        "your",
        "yours",
        "yourself",
        "yourselves",
    }
)


__all__ = ["ENGLISH_STOPWORDS"]
